import json
import os
import datetime

SHARED_PLAYLISTS_FILE = "shared_playlists.json"
FAVOURITES_FILE = "favourites_{username}.json"

# ─── Shared Playlists ───────────────────────────────────────────────

def load_shared_playlists():
    if os.path.exists(SHARED_PLAYLISTS_FILE):
        with open(SHARED_PLAYLISTS_FILE) as f:
            return json.load(f)
    return []

def save_shared_playlists(data):
    with open(SHARED_PLAYLISTS_FILE, 'w') as f:
        json.dump(data, f)

def share_playlist(username, songs, mood, note=""):
    playlists = load_shared_playlists()
    entry = {
        "id": len(playlists) + 1,
        "username": username,
        "mood": mood,
        "note": note,
        "songs": songs,
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "likes": 0,
        "liked_by": []
    }
    playlists.append(entry)
    save_shared_playlists(playlists)

def like_shared_playlist(playlist_id, username):
    playlists = load_shared_playlists()
    for p in playlists:
        if p["id"] == playlist_id:
            if username not in p["liked_by"]:
                p["liked_by"].append(username)
                p["likes"] += 1
    save_shared_playlists(playlists)

# ─── Favourites ─────────────────────────────────────────────────────

def _fav_file(username):
    return f"favourites_{username}.json"

def load_favourites(username):
    f = _fav_file(username)
    if os.path.exists(f):
        with open(f) as fp:
            return json.load(fp)
    return []

def toggle_favourite(username, song_name, mood, genre):
    favs = load_favourites(username)
    names = [s["song"] for s in favs]
    if song_name in names:
        favs = [s for s in favs if s["song"] != song_name]
        action = "removed"
    else:
        favs.append({"song": song_name, "mood": mood, "genre": genre,
                     "added": datetime.datetime.now().strftime("%Y-%m-%d")})
        action = "added"
    with open(_fav_file(username), 'w') as f:
        json.dump(favs, f)
    return action

def export_playlist_text(username, songs, mood):
    lines = [f"🎵 {username}'s {mood} Playlist — PLM Devs AI", "=" * 40]
    for i, s in enumerate(songs, 1):
        lines.append(f"{i}. {s['song']} ({s['mood']} / {s['genre']})")
    lines.append("\nGenerated by PLM Devs AI Music Recommender")
    return "\n".join(lines)
