import json
import os
import datetime

SHARED_PLAYLISTS_FILE = "shared_playlists.json"
FAVOURITES_FILE = "favourites_{username}.json"
FRIENDS_FILE = "friends_{username}.json"
LEADERBOARD_FILE = "leaderboard.json"

# ─── Shared Playlists ───────────────────────────────────────────────

def load_shared_playlists():
    if os.path.exists(SHARED_PLAYLISTS_FILE):
        with open(SHARED_PLAYLISTS_FILE) as f:
            return json.load(f)
    return []

def save_shared_playlists(data):
    with open(SHARED_PLAYLISTS_FILE, 'w') as f:
        json.dump(data, f)

def share_playlist(username, songs, mood, note=""):
    playlists = load_shared_playlists()
    entry = {
        "id": len(playlists) + 1,
        "username": username,
        "mood": mood,
        "note": note,
        "songs": songs,
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "likes": 0,
        "liked_by": []
    }
    playlists.append(entry)
    save_shared_playlists(playlists)

def like_shared_playlist(playlist_id, username):
    playlists = load_shared_playlists()
    for p in playlists:
        if p["id"] == playlist_id:
            if username not in p["liked_by"]:
                p["liked_by"].append(username)
                p["likes"] += 1
    save_shared_playlists(playlists)

# ─── Favourites ─────────────────────────────────────────────────────

def _fav_file(username):
    return f"favourites_{username}.json"

def load_favourites(username):
    f = _fav_file(username)
    if os.path.exists(f):
        with open(f) as fp:
            return json.load(fp)
    return []

def toggle_favourite(username, song_name, mood, genre):
    favs = load_favourites(username)
    names = [s["song"] for s in favs]
    if song_name in names:
        favs = [s for s in favs if s["song"] != song_name]
        action = "removed"
    else:
        favs.append({"song": song_name, "mood": mood, "genre": genre,
                     "added": datetime.datetime.now().strftime("%Y-%m-%d")})
        action = "added"
    with open(_fav_file(username), 'w') as f:
        json.dump(favs, f)
    return action

def export_playlist_text(username, songs, mood):
    lines = [f"🎵 {username}'s {mood} Playlist — PLM Devs AI", "=" * 40]
    for i, s in enumerate(songs, 1):
        lines.append(f"{i}. {s['song']} ({s['mood']} / {s['genre']})")
    lines.append("\nGenerated by PLM Devs AI Music Recommender")
    return "\n".join(lines)

# ─── Friend System ──────────────────────────────────────────────────

def _friends_file(username):
    return f"friends_{username}.json"

def load_friends(username):
    f = _friends_file(username)
    if os.path.exists(f):
        with open(f) as fp:
            return json.load(fp)
    return {"following": [], "followers": []}

def save_friends(username, friends_data):
    with open(_friends_file(username), 'w') as f:
        json.dump(friends_data, f)

def follow_user(follower, following):
    """This user follows another user"""
    if follower == following:
        return False, "Cannot follow yourself"
    
    # Add to follower's following list
    follower_data = load_friends(follower)
    if following not in follower_data["following"]:
        follower_data["following"].append(following)
        save_friends(follower, follower_data)
    
    # Add to followed user's followers list
    following_data = load_friends(following)
    if follower not in following_data["followers"]:
        following_data["followers"].append(follower)
        save_friends(following, following_data)
    
    return True, f"Now following {following}"

def unfollow_user(follower, following):
    """This user unfollows another user"""
    # Remove from follower's following list
    follower_data = load_friends(follower)
    if following in follower_data["following"]:
        follower_data["following"].remove(following)
        save_friends(follower, follower_data)
    
    # Remove from followed user's followers list
    following_data = load_friends(following)
    if follower in following_data["followers"]:
        following_data["followers"].remove(follower)
        save_friends(following, following_data)
    
    return True, f"Unfollowed {following}"

# ─── Leaderboard ────────────────────────────────────────────────────

def load_leaderboard():
    """Load global leaderboard (top users by XP)"""
    if os.path.exists(LEADERBOARD_FILE):
        try:
            with open(LEADERBOARD_FILE) as f:
                return json.load(f)
        except:
            return []
    return []

def save_leaderboard(data):
    with open(LEADERBOARD_FILE, 'w') as f:
        json.dump(data, f)

def update_leaderboard(username, xp, level):
    """Update user's position in leaderboard"""
    leaderboard = load_leaderboard()
    
    # Remove if exists
    leaderboard = [u for u in leaderboard if u["username"] != username]
    
    # Add updated entry
    leaderboard.append({
        "username": username,
        "xp": xp,
        "level": level,
        "updated": datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    })
    
    # Sort by XP descending
    leaderboard.sort(key=lambda x: x["xp"], reverse=True)
    save_leaderboard(leaderboard)

def get_leaderboard_top(limit=20):
    """Get top N users from leaderboard"""
    leaderboard = load_leaderboard()
    return leaderboard[:limit]

def get_user_rank(username):
    """Get user's rank in leaderboard"""
    leaderboard = load_leaderboard()
    for i, user in enumerate(leaderboard, 1):
        if user["username"] == username:
            return i, user["xp"]
    return None, None

