import json
import os
import datetime

_BASE = os.path.dirname(os.path.abspath(__file__))
SHARED_PLAYLISTS_FILE = os.path.join(_BASE, "shared_playlists.json")
LEADERBOARD_FILE      = os.path.join(_BASE, "leaderboard.json")

def load_shared_playlists():
    if os.path.exists(SHARED_PLAYLISTS_FILE):
        with open(SHARED_PLAYLISTS_FILE) as f:
            return json.load(f)
    return []

def save_shared_playlists(data):
    with open(SHARED_PLAYLISTS_FILE, 'w') as f:
        json.dump(data, f)

def share_playlist(username, songs, mood, note=""):
    playlists = load_shared_playlists()
    playlists.append({
        "id": len(playlists) + 1, "username": username, "mood": mood,
        "note": note, "songs": songs,
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "likes": 0, "liked_by": [], "comments": []
    })
    save_shared_playlists(playlists)

def like_shared_playlist(playlist_id, username):
    playlists = load_shared_playlists()
    for p in playlists:
        if p["id"] == playlist_id and username not in p.get("liked_by", []):
            p.setdefault("liked_by", []).append(username)
            p["likes"] = p.get("likes", 0) + 1
    save_shared_playlists(playlists)

def _fav_file(username):
    return os.path.join(_BASE, f"favourites_{username}.json")

def load_favourites(username):
    f = _fav_file(username)
    if os.path.exists(f):
        with open(f) as fp: return json.load(fp)
    return []

def toggle_favourite(username, song_name, mood, genre):
    favs = load_favourites(username)
    if song_name in [s["song"] for s in favs]:
        favs = [s for s in favs if s["song"] != song_name]; action = "removed"
    else:
        favs.append({"song": song_name, "mood": mood, "genre": genre,
                     "added": datetime.datetime.now().strftime("%Y-%m-%d")}); action = "added"
    with open(_fav_file(username), 'w') as f: json.dump(favs, f)
    return action

def export_playlist_text(username, songs, mood):
    lines = [f"🎵 {username}'s {mood} Playlist — PLM Devs AI", "="*40]
    for i, s in enumerate(songs, 1):
        lines.append(f"{i}. {s['song']} ({s['mood']} / {s['genre']})")
    lines.append("\nGenerated by PLM Devs AI Music Recommender")
    return "\n".join(lines)

def _friends_file(username):
    return os.path.join(_BASE, f"friends_{username}.json")

def load_friends(username):
    f = _friends_file(username)
    if os.path.exists(f):
        with open(f) as fp: return json.load(fp)
    return {"following": [], "followers": []}

def save_friends(username, data):
    with open(_friends_file(username), 'w') as f: json.dump(data, f)

def follow_user(follower, following):
    if follower == following: return False, "Cannot follow yourself"
    fd = load_friends(follower)
    if following not in fd["following"]: fd["following"].append(following); save_friends(follower, fd)
    gd = load_friends(following)
    if follower not in gd["followers"]: gd["followers"].append(follower); save_friends(following, gd)
    return True, f"Now following {following}"

def unfollow_user(follower, following):
    fd = load_friends(follower)
    if following in fd["following"]: fd["following"].remove(following); save_friends(follower, fd)
    gd = load_friends(following)
    if follower in gd["followers"]: gd["followers"].remove(follower); save_friends(following, gd)
    return True, f"Unfollowed {following}"

def load_leaderboard():
    if os.path.exists(LEADERBOARD_FILE):
        try:
            with open(LEADERBOARD_FILE) as f: return json.load(f)
        except Exception: return []
    return []

def save_leaderboard(data):
    with open(LEADERBOARD_FILE, 'w') as f: json.dump(data, f)

def update_leaderboard(username, xp, level):
    lb = [u for u in load_leaderboard() if u["username"] != username]
    lb.append({"username": username, "xp": xp, "level": level,
                "updated": datetime.datetime.now().strftime("%Y-%m-%d %H:%M")})
    lb.sort(key=lambda x: x["xp"], reverse=True)
    save_leaderboard(lb)

def get_leaderboard_top(limit=20):
    return load_leaderboard()[:limit]

def get_user_rank(username):
    for i, u in enumerate(load_leaderboard(), 1):
        if u["username"] == username: return i, u["xp"]
    return None, None

def add_comment(playlist_id: int, username: str, text: str):
    playlists = load_shared_playlists()
    for p in playlists:
        if p["id"] == playlist_id:
            p.setdefault("comments", []).append({
                "username": username, "text": text.strip(),
                "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M")})
    save_shared_playlists(playlists)

def get_comments(playlist_id: int) -> list:
    for p in load_shared_playlists():
        if p["id"] == playlist_id: return p.get("comments", [])
    return []
